# Generated by Django 5.1.6 on 2025-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='client_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='client_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
