# Generated by Django 5.1.6 on 2025-05-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alertlog_client_id_sensor_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
    ]
