# Generated by Django 5.1.6 on 2025-05-11 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alertlog_client_id_alter_sensor_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100)),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.sensor')),
            ],
            options={
                'verbose_name': 'Device History',
                'verbose_name_plural': 'Device Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
